.Dd 2018-04-11
.Dt FF2PAM 1
.Os suckless.org
.Sh NAME
.Nm ff2pam
.Nd convert farbfeld to PAM
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
reads a
.Xr farbfeld 5
image from stdin, converts it to PAM (16-bit RGBA) and writes the result
to stdout.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh EXAMPLES
$
.Nm
< image.ff > image.pam
.Pp
$ bunzip2 < image.ff.bz2 |
.Nm
> image.pam
.Sh SEE ALSO
.Xr bzip2 1 ,
.Xr farbfeld 5
.Sh AUTHORS
.An Mattias Andrée Aq Mt maandree@kth.se
